// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8Af_VMaF5eIILu3v_mDGaPsd_AYulqX8',
    appId: '1:851104808206:web:f34e76cbf6c859b1176b5f',
    messagingSenderId: '851104808206',
    projectId: 'bellukstudio-8abde',
    authDomain: 'bellukstudio-8abde.firebaseapp.com',
    storageBucket: 'bellukstudio-8abde.firebasestorage.app',
    measurementId: 'G-R0YCC8PQK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZiOrgWiylyeLkjcDmoV7ZW04UhNVQg8Q',
    appId: '1:851104808206:android:520fffe02bde7996176b5f',
    messagingSenderId: '851104808206',
    projectId: 'bellukstudio-8abde',
    storageBucket: 'bellukstudio-8abde.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxRuCBwHur8Ao1NOjT04pzJSEchewZx7I',
    appId: '1:851104808206:ios:1dbfa116d109d8e8176b5f',
    messagingSenderId: '851104808206',
    projectId: 'bellukstudio-8abde',
    storageBucket: 'bellukstudio-8abde.firebasestorage.app',
    iosBundleId: 'com.bellukstudio.multiwhatsappweb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxRuCBwHur8Ao1NOjT04pzJSEchewZx7I',
    appId: '1:851104808206:ios:087897b811a31744176b5f',
    messagingSenderId: '851104808206',
    projectId: 'bellukstudio-8abde',
    storageBucket: 'bellukstudio-8abde.firebasestorage.app',
    iosBundleId: 'com.bellukstudio.multiWhatsappWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8Af_VMaF5eIILu3v_mDGaPsd_AYulqX8',
    appId: '1:851104808206:web:88c953161746f924176b5f',
    messagingSenderId: '851104808206',
    projectId: 'bellukstudio-8abde',
    authDomain: 'bellukstudio-8abde.firebaseapp.com',
    storageBucket: 'bellukstudio-8abde.firebasestorage.app',
    measurementId: 'G-9C91XJWFGR',
  );
}
