; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only.
;
; CATATAN (versi CI-friendly):
; - Semua path sekarang RELATIF terhadap folder tempat file .iss ini berada
;   (folder "compiler/"), bukan hardcode "D:\multi_whatsapp_web\...".
;   Jadi script ini jalan di laptop manapun ATAU di GitHub Actions runner.
; - MyAppVersion diambil dari environment variable APP_VERSION, yang di-set
;   oleh workflow GitHub Actions (env: APP_VERSION: ${{ inputs.version }}).
;   Kalau dijalankan manual tanpa set APP_VERSION, akan fallback ke "0.0.0".
; - [Files] sekarang pakai wildcard ke seluruh folder Release, jadi tidak
;   perlu update satu-satu tiap kali ada plugin baru/berubah.

#define MyAppName "Multi Whatsapp Web"
#define MyAppVersion GetEnv("APP_VERSION")
#define MyAppPublisher "BellukStudio, Inc."
#define MyAppURL "https://bellukdev.vercel.app"
#define MyAppExeName "multi_whatsapp_web.exe"
#define MyAppAssocName MyAppName + ""
#define MyAppAssocExt ".myp"
#define MyAppAssocKey StringChange(MyAppAssocName, " ", "") + MyAppAssocExt
#define DoubleAmp(Value) StringChange(Value, "&", "&&")
#define EscapeConstArgument(Value) StringChange(StringChange(StringChange(Value, "%", "%25"), ",", "%2c"), "}", "%7d")

#if MyAppVersion == ""
  #define MyAppVersion "0.0.0"
#endif

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
AppId={{F9743FBE-DE4D-418D-8CCF-09782F65C27D}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the install be done in "64-bit mode" on x64 or Windows 11 on Arm.
ArchitecturesInstallIn64BitMode=x64compatible
ChangesAssociations=yes
DisableProgramGroupPage=yes
; LicenseFile dihapus — tambahkan lagi kalau kamu sudah punya file lisensi,
; taruh misalnya di compiler\Licence.txt lalu uncomment baris di bawah:
LicenseFile=..\Licence.txt
OutputDir=Output
OutputBaseFilename=multi_whatsapp_web_setup_{#MyAppVersion}
SetupIconFile=..\assets\icon.ico
SolidCompression=yes
WizardStyle=modern dynamic windows11

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; Seluruh isi folder build Release (exe, dll plugin, folder data) diambil
; langsung lewat wildcard, jadi otomatis ikut kalau ada plugin baru.
Source: "..\build\windows\x64\runner\Release\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; Redistributable VC++ runtime (sudah ada di folder compiler/ ini, bukan D:\)
Source: "msvcp140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "vcruntime140.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "vcruntime140_1.dll"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files.

[Registry]
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocExt}\OpenWithProgids"; ValueType: string; ValueName: "{#MyAppAssocKey}"; ValueData: ""; Flags: uninsdeletevalue
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}"; ValueType: string; ValueName: ""; ValueData: "{#MyAppAssocName}"; Flags: uninsdeletekey
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\DefaultIcon"; ValueType: string; ValueName: ""; ValueData: "{app}\{#MyAppExeName},0"
Root: HKA; Subkey: "Software\Classes\{#MyAppAssocKey}\shell\open\command"; ValueType: string; ValueName: ""; ValueData: """{app}\{#MyAppExeName}"" ""%1"""

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#DoubleAmp(MyAppName)}}"; Flags: nowait postinstall skipifsilent
